### ISSUE TITLE
== my_account_hook not found.

### ISSUE THREAD

**Issue by arrosado** [ubik/redmine_local_avatars#3]
I've cloned the repository into my redmine plugins folder and its not working, It seems to be referencing a file called my_account_hook in the init.rb file which is not found on the lib folder of the plugin. I'm currently using Redmine 1.4.4 stable which is the default TurnKey linux redmine installation. Maybe the files need to be added to the repo or am I missing something?

Thanks in advance, 

Ariel Rosado Rivera

**Comment by ubik** [comment]
Maybe I have missed these files. I don't support this plugin anymore. 
Please try one of forks, there are Redmine 1.4 and 2.0-compatible versions.
